### ISSUE TITLE
Associativity?

### ISSUE THREAD

**Issue by ihu5** [michael-ross-scott/Cache-Simulator#1]
Does your code support associativity of cache (n-set, fully, direct)?

I run the code successfully but I do not know how to use associativity

**Comment by michael-ross-scott** [comment]
This is a pretty old project for an assignment at university, so I really doubt that it would. I'll try to update the project README when I get the chance. For the moment here is just an example input file which was meant to run the simulator.

[matmul5x5_loop.addr.txt](https://github.com/michael-ross-scott/Cache-Simulator/files/3675905/matmul5x5_loop.addr.txt)

**Comment by michael-ross-scott** [comment]
Ah, I see there are already example files. I looked a bit more into this issue and unfortunately, this repo was not built with associativity in mind.
